name: hajj_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter 

  dio: ^5.9.1
  dartz: ^0.10.1
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  device_info_plus: ^12.3.0
  device_preview: ^1.3.1

  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4

  go_router: ^17.1.0

  syrian_dio: ^0.0.2

  flutter_localizations:
    sdk: flutter
  iconsax: ^0.0.8
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter # Flutterâ€™s built-in testing framework

  flutter_lints: ^6.0.0 # Recommended lint rules to keep code clean and consistent

flutter:
  uses-material-design: true # Enables Material icons and Material styling
  assets:
    - assets/images/
    - assets/lang/
